import jsPDF from 'jspdf';

interface PDFOptions {
  title: string;
  content: string;
  filename?: string;
}

export function generatePDF({ title, content, filename = 'article.pdf' }: PDFOptions) {
  const doc = new jsPDF();
  
  // Set font
  doc.setFont('helvetica');
  
  // Title
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text(title, 20, 30);
  
  // Content
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  
  // Split content into lines that fit the page width
  const pageWidth = doc.internal.pageSize.width;
  const margin = 20;
  const maxLineWidth = pageWidth - (margin * 2);
  
  const lines = doc.splitTextToSize(content || 'Your article content will appear here...', maxLineWidth);
  
  let yPosition = 50;
  const lineHeight = 7;
  const pageHeight = doc.internal.pageSize.height;
  
  lines.forEach((line: string) => {
    if (yPosition > pageHeight - 30) {
      doc.addPage();
      yPosition = 30;
    }
    
    doc.text(line, margin, yPosition);
    yPosition += lineHeight;
  });
  
  // Footer
  const pageCount = doc.internal.pages.length - 1;
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(
      `Generated by Neocortical Extension Layer • Page ${i}`,
      pageWidth / 2,
      pageHeight - 15,
      { align: 'center' }
    );
  }
  
  // Download the PDF
  doc.save(filename);
}
