import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Download, X } from "lucide-react";

interface PDFPreviewModalProps {
  isOpen: boolean;
  onClose: () => void;
  onDownload: () => void;
  title: string;
  content: string;
}

export default function PDFPreviewModal({ isOpen, onClose, onDownload, title, content }: PDFPreviewModalProps) {
  const formatContent = (htmlContent: string) => {
    // If content contains HTML, render it directly
    if (htmlContent.includes('<')) {
      return <div dangerouslySetInnerHTML={{ __html: htmlContent }} className="space-y-4" />;
    }
    
    // Otherwise, treat as plain text and split by lines
    return htmlContent.split('\n').map((paragraph, index) => (
      <p key={index} className="mb-4 leading-relaxed">
        {paragraph}
      </p>
    ));
  };

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="max-w-4xl max-h-[90vh] overflow-hidden">
        <DialogHeader>
          <div className="flex items-center justify-between">
            <DialogTitle>PDF Preview</DialogTitle>
            <div className="flex items-center space-x-3">
              <Button onClick={onDownload}>
                <Download className="mr-2 h-4 w-4" />
                Download PDF
              </Button>
              <Button variant="ghost" size="sm" onClick={onClose}>
                <X className="h-4 w-4" />
              </Button>
            </div>
          </div>
        </DialogHeader>
        <div className="overflow-y-auto max-h-[70vh]">
          {/* PDF Preview Content */}
          <div className="bg-gray-100 p-8">
            <div className="bg-white shadow-lg max-w-2xl mx-auto p-8" style={{ aspectRatio: '8.5/11' }}>
              <h1 className="text-3xl font-bold text-gray-900 mb-6">{title}</h1>
              <div className="space-y-4 text-gray-800 leading-relaxed">
                {formatContent(content || "Your article content will appear here...")}
              </div>
              <div className="mt-8 pt-4 border-t border-gray-200 text-sm text-gray-500 text-center">
                <p>Generated by Neocortical Extension Layer • Page 1</p>
              </div>
            </div>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
